### ISSUE TITLE
summary.surcharge and summary.shippingamound mixed up

### ISSUE THREAD

**Issue by knitzie** [sofa/sofa-checkout-service#9] opened 2015-02-18 09:26 UTC
Hi,

I think there's a small assignment bug inside the sofa.checkoutservice.QuoteRequester
The requested object contains the shippingAmount parameter, which actually is the surcharge fee (in our case?).

**Comment by cburgdorf** [comment] 2015-02-18 09:49
It's not a bug in the checkoutService it's a hack made in this particular project. Basically we were asked to label the shippingAmount in the UI to "Handlingpauschale" and then put an unbound shipping amount label on the screen that just displays 0. So, yeah, things look odd under the cover but they are intentionally ;)

Closing here. Feel free to reopen in case you have further question. But we can discuss this in private space, too.

**Closed as completed by cburgdorf** 2015-02-18 09:49 UTC
